apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: jenkins-host
  namespace: emissary
  annotations:
     external-dns.ambassador-service: sre-blueprint-dev-00-cluster-emissary-emissary-ingress.emissary
spec:
  hostname: jenkins-test.sre.aws.dev.e-comm
  acmeProvider:
      authority: none
  tlsSecret:
    name: emissary-certificate
    namespace: emissary
  # requestPolicy:
  #   insecure:
  #     action: Route

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: jenkins-mapping
  namespace: emissary
spec:
  prefix: /
  service: jenkins.jenkins.svc.cluster.local:80
  host: jenkins-test.sre.aws.dev.e-comm