apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    service.beta.kubernetes.io/aws-load-balancer-type: {{ .Values.service.elb_type }}
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.elb_int_ext }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: jenkins
  type: {{ .Values.service.type }}

